### ISSUE TITLE
Make upload-csvs more discoverable by adding a link to Datasette's top level nav

### ISSUE THREAD

**Issue by obra** [simonw/datasette-upload-csvs#15]
It'd be lovely to not have to remember the path /-/upload-csvs, but to have somewhere in the app's UI that shows a way to navigate there if the plugin is enabled and available.

**Comment by simonw** [comment]
Definitely need to do this. It's currently blocked on a plugin hook mechanism for supporting this: https://github.com/simonw/datasette/issues/690

**Comment by simonw** [comment]
Blocked awaiting https://github.com/simonw/datasette/issues/1064

**Comment by simonw** [comment]
Add this to the Datasette documentation for the `menu_links` plugin hook once this plugin has been  upgraded:

    Example: `datasette-upload-csvs <https://github.com/simonw/datasette-upload-csvs>`_

**Comment by simonw** [comment]
Datasette 0.51 is out, so this is unblocked.
